---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-credentials
  namespace: demo-secrets
spec:
  encryptedData:
    api-token: AgB2svt6CRZyRG7ufTxEeATGQZVwAjDeJvNBsrDPmQB741FqPDc8AALEtU8l7AMsZSzgAiM3veluHI9OeGmc0+lL2xgYbvIwfY0NWFGTaMBMi6Qw2kuUjFh1ciM7NhUFLXle6GAey4Txzuh+geuji32LcLD2PbK+ZUOvXjFUUh1h7P9ZuaU7QqyRdmd/CNEF3b7a2MwKh4mE/h4VW/m4tBUNdwP/zavqirQ3E6K7jJCPCjOg/NiTKJI1sgjw6gBPaPcEeARNYVBCPAXDvFK27I3tPFL3FryYGxZq55QdtVHgUfyhb8raEN61d2xQVKpRPdU53+6rsXqw285G+WU/aNBnPDaY649UKz9K2Qf4V/2FBE5uMMsG9ENFqZkC2iVOoO+mtG71W9mnNkY3pVjb6GyKYHERSr8KUHJX7U9dAsBolH8NsrnXwdzD91s689y+DWeQwcPXiZAs/t7ZR7tKbgCsxcf+ktRIF0Hik8UVTxOfx1St7DkTX/MgPtRdodKOBORGNd6lNSi92TbIfYMrDm/isgHqLDNa3k5MtBYiQLXr4244WwrnSemuiDmFFSuEAaLPe4nf4Re0drA43UvUdK+6ebpN887mI6Kpw/SGtb2HopZz0y4QjxaDW2izLlFjbglQdHjpSL+RAWsEFK08k6h0wilVI+CJ44K8V/1OePqaqkyJFETm0FY2rKxaHzkRAR5Xzmryp8r2s1bCjFCZMCW7cIkmegtCtJ5rVwi/
    db-password: AgCa8sOUWtZ5NtfE7qd46yOqJXpGejovDStcerpUk1j6ggppnNrLjNLde6NdBz6yJKT2jjVyDClxKR/7eleV7o15kS+P8hgLRSz2Wo9KXVP3D0pzBu3lhc8KUd3zLhL1aPouHZuK2h8HZbeq0FoC3XSg+lNYlChbCFOw3z4KaJyJUaDjzWirCy4NUQ01ru9BYly0WpkO3vpRaN26kBAYwAvXXKIviBs73XPj6XfYTlPRxkT+IwLIxrtZJ0ZvguJVXferW8aFe8W+F3h3f0a3LqJNR+fbM8WizFbyrgNbSbHbuH7rMWXFotl1cYHUhTS6PC5snktygd1Xj4OrMCENL05XaGRrafGgN4bMirImo3hUucXM1++DyuMeHdW9TvBAx9Xdq0qBkBnkJeA5WidTlVjz8hVNrd6OjlaPkePgo+kqhNlthQTQ+wjPKn+vZPABsnJRP9P2Oguk0jNc1H98Lu5hT9M7N23sf0nNkWUerHZF8jQs52MJt/Tpqavtu35uNTSS0Am1vVKgEOiFUQEM7QHj+rPARGS4Eg3cKh68LOh7NjcBuIJGFHsn6GdsJbFMi7e81cVVOoEebl1pn4NOIrEt5mFS9omHo9+IZjC29ewcJZkDkHCLQ4Hw51d9BUud1LujD/N6XMs3o6/LvLHbZyB37FmnFz1UObU+m5xiOtf9BtsuZr8Hws9DoCx5bCqqbX6SK5a+b8z4IzR5ZGW+CehjH4LUmB6g/lE=
  template:
    metadata:
      name: demo-credentials
      namespace: demo-secrets
    type: Opaque
