# The useful bit: Terraform writes the Ansible inventory. No copy-pasting IPs
# between two tools, which is the whole point of having both.
#
# It also passes through the EBS VOLUME ID for each node. On Nitro instances the
# kernel device name (/dev/nvme1n1) is assigned in attach order and is not
# stable, so the volume ID is the only deterministic handle on the disk --
# /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_<id-without-dash>. Terraform
# knows it; Ansible needs it; the inventory is the seam between them.

resource "local_file" "inventory" {
  filename        = "${path.module}/../../inventory/hosts.ini"
  file_permission = "0644"

  # join(split(trimspace)) flattens the per-line indentation that Terraform's
  # %{for} / %{if} directives leave behind. The <<- heredoc strips only the
  # MINIMUM common indent, so anything a directive emits keeps its extra spaces
  # -- which turns "[k8s]" into "    [k8s]". Ansible's INI parser happens to
  # tolerate that today; an inventory that depends on it is a trap.
  content = join("\n", [for line in split("\n", <<-INI
    # GENERATED BY TERRAFORM -- do not edit by hand.
    # Regenerate with: terraform apply

    [elastic]
    %{for i, inst in aws_instance.es~}
    es-0${i + 1} ansible_host=${inst.public_ip} private_ip=${inst.private_ip} elastic_node_roles="master,data"%{if var.data_volume_gb > 0} es_data_volume_id=${aws_ebs_volume.es_data[i].id}%{endif}
    %{endfor~}

    [kibana]
    es-01

    [minio]
    es-01

    [postgres]
    es-01

    # Both nodes are in [k8s] and the kubernetes role branches on
    # k8s_distribution, so the SAME role installs k3s on one and RKE2 on the
    # other. That is the whole argument of drills/07 expressed as inventory.
    %{if var.create_k8s_node~}
    [k8s]
    k3s-01 ansible_host=${aws_instance.k8s[0].public_ip} private_ip=${aws_instance.k8s[0].private_ip} k8s_distribution=k3s
    %{endif~}
    %{if var.create_rancher_node~}
    rke2-01 ansible_host=${aws_instance.rancher[0].public_ip} private_ip=${aws_instance.rancher[0].private_ip} k8s_distribution=rke2
    %{endif~}

    [all:vars]
    %{if var.create_rds~}
    # RDS is a managed ENDPOINT, not a host -- there is no sshd on it and no
    # [rds] group, because Ansible has nothing to connect to. It is also not
    # publicly reachable, so the control machine cannot see it either.
    #
    # It is therefore configured THROUGH a host that can reach it:
    # playbooks/rds.yml runs on es-01 (inside the VPC, in the lab security
    # group) and points community.postgresql at this endpoint via login_host.
    rds_endpoint=${aws_db_instance.postgres[0].address}
    rds_port=${aws_db_instance.postgres[0].port}
    rds_master_username=${var.rds_master_username}
    %{endif~}
    ansible_user=ubuntu
    ansible_python_interpreter=/usr/bin/python3
    ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    private_iface=ens5
  INI
  ) : trimspace(line)])
}

output "elasticsearch_public_ips" {
  value = aws_instance.es[*].public_ip
}

output "elasticsearch_private_ips" {
  value = aws_instance.es[*].private_ip
}

output "es_data_volume_ids" {
  description = "Attached EBS data volumes. Empty when data_volume_gb = 0."
  value       = aws_ebs_volume.es_data[*].id
}

output "k3s_public_ip" {
  value = var.create_k8s_node ? aws_instance.k8s[0].public_ip : null
}

output "rke2_public_ip" {
  value = var.create_rancher_node ? aws_instance.rancher[0].public_ip : null
}

output "rds_endpoint" {
  description = "Managed PostgreSQL. Reachable only from inside the VPC -- see the SG."
  value       = var.create_rds ? aws_db_instance.postgres[0].endpoint : null
}

output "rds_password" {
  description = "Generated, not typed. Read with: terraform output -raw rds_password"
  value       = var.create_rds ? random_password.rds[0].result : null
  sensitive   = true
}

output "next_steps" {
  value = <<-EOT

    Inventory written to inventory/hosts.ini

      ansible all -m ping
      ansible-playbook playbooks/site.yml --ask-vault-pass

    Kibana   http://${aws_instance.es[0].public_ip}:5601
    MinIO    http://${aws_instance.es[0].public_ip}:9001
    ES       export ES=http://${aws_instance.es[0].public_ip}:9200
    %{if var.create_k8s_node~}
    Rancher  https://rancher.${aws_instance.k8s[0].public_ip}.sslip.io
    Kong     http://${aws_instance.k8s[0].public_ip}:30080/demo
    %{endif~}
    %{if var.create_rds~}
    RDS      ${aws_db_instance.postgres[0].endpoint}
             ansible-playbook playbooks/rds.yml --ask-vault-pass
    %{endif~}

    WHEN YOU ARE DONE:  terraform destroy
  EOT
}
