terraform {
  required_version = ">= 1.5"
  required_providers {
    hcloud = { source = "hetznercloud/hcloud", version = "~> 1.48" }
    local  = { source = "hashicorp/local", version = "~> 2.4" }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}

variable "hcloud_token" {
  type      = string
  sensitive = true
}

variable "prefix" {
  type    = string
  default = "andrei-lab"
}

variable "location" {
  type    = string
  default = "nbg1" # Nuremberg -- closest to Romania
}

variable "es_server_type" {
  description = "cx22 = 2 vCPU / 4 GB, ~EUR 4.50/mo"
  type        = string
  default     = "cx22"
}

variable "k8s_server_type" {
  description = "cx32 = 4 vCPU / 8 GB, ~EUR 8/mo -- Rancher needs the headroom"
  type        = string
  default     = "cx32"
}

variable "ssh_public_key_path" {
  type    = string
  default = "~/.ssh/id_ed25519.pub"
}

resource "hcloud_ssh_key" "lab" {
  name       = "${var.prefix}-key"
  public_key = file(var.ssh_public_key_path)
}

resource "hcloud_network" "lab" {
  name     = "${var.prefix}-net"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "lab" {
  network_id   = hcloud_network.lab.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/24"
}

resource "hcloud_firewall" "lab" {
  name = "${var.prefix}-fw"

  dynamic "rule" {
    for_each = ["22", "5601", "9000-9001", "9200", "443", "30000-32767"]
    content {
      direction  = "in"
      protocol   = "tcp"
      port       = rule.value
      source_ips = [var.my_ip_cidr]
    }
  }
}

variable "my_ip_cidr" {
  description = "curl -s ifconfig.me"
  type        = string
}

resource "hcloud_server" "es" {
  count        = 3
  name         = "${var.prefix}-es-0${count.index + 1}"
  image        = "ubuntu-24.04"
  server_type  = var.es_server_type
  location     = var.location
  ssh_keys     = [hcloud_ssh_key.lab.id]
  firewall_ids = [hcloud_firewall.lab.id]

  network {
    network_id = hcloud_network.lab.id
    ip         = "10.0.0.1${count.index + 1}"
  }

  depends_on = [hcloud_network_subnet.lab]
}

resource "hcloud_server" "k8s" {
  name         = "${var.prefix}-k3s-01"
  image        = "ubuntu-24.04"
  server_type  = var.k8s_server_type
  location     = var.location
  ssh_keys     = [hcloud_ssh_key.lab.id]
  firewall_ids = [hcloud_firewall.lab.id]

  network {
    network_id = hcloud_network.lab.id
    ip         = "10.0.0.21"
  }

  depends_on = [hcloud_network_subnet.lab]
}

resource "local_file" "inventory" {
  filename        = "${path.module}/../../inventory/hosts.ini"
  file_permission = "0644"

  content = <<-INI
    # GENERATED BY TERRAFORM -- do not edit by hand.

    [elastic]
    %{for i, s in hcloud_server.es~}
    es-0${i + 1} ansible_host=${s.ipv4_address} private_ip=10.0.0.1${i + 1} elastic_node_roles="master,data"
    %{endfor~}

    [kibana]
    es-01

    [minio]
    es-01

    [postgres]
    es-01

    [k8s]
    k3s-01 ansible_host=${hcloud_server.k8s.ipv4_address} private_ip=10.0.0.21

    [all:vars]
    ansible_user=root
    ansible_python_interpreter=/usr/bin/python3
    ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    private_iface=enp7s0
  INI
}

output "next_steps" {
  value = <<-EOT

    Inventory written to inventory/hosts.ini

      ansible all -m ping
      ansible-playbook playbooks/site.yml --ask-vault-pass

    Kibana   http://${hcloud_server.es[0].ipv4_address}:5601
    ES       export ES=http://${hcloud_server.es[0].ipv4_address}:9200
    Rancher  https://rancher.${hcloud_server.k8s.ipv4_address}.sslip.io

    Cost is roughly EUR 21/month while running.
    Snapshot and destroy when idle:  terraform destroy
  EOT
}
