apiVersion: v1
kind: Secret
metadata:
    name: demo-credentials
    namespace: demo-secrets
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8TUHGpXrMsyrLuPbK4vhyDNhgP4O22DfdTxlqQ==,iv:H2BmzLysJNjEOqoVLJz9Wk66d2hlCmkE2P9l7/b34zc=,tag:0q4e6JxRmaj/2ABnsIVeRw==,type:str]
    db-password: ENC[AES256_GCM,data:Bu6VPILqwPLeDvrDLqdQn8kOBvYUaKW1,iv:SKNju+2TQJ9lEqx6RQzkvipk3AUPL+J5qXECBUN+96E=,tag:NDnJBY9CcrYaISfk7pEfag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSE5yL3dFSks5VTlSdmVR
            aGR1a1JiMjljNzV3Um1qa09QemFGK3N2TUY0CkZXaTVyN3E5WDJPTHdNcjVESG1G
            bjEzcGpGcmlpbXJ3UUdIRWNEOVVrL0UKLS0tIHk4a2lJK0tib21HV3E4Q21jRitU
            RTJrN05LenhUblE1RVczbVM0QmJBbzQKOzZPsfZsMYUcN4MgFnzENRSo5O3PzlEH
            mRIQTbS1LvGzU8GzqXXDLBLNvdUQjeGtfYvDoL2idqdj5CPKyf7xCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfl2s042smqk7dmjkkynwg4dhycjg7xeds2zt6pgyrl6pyzvy9dq764zde
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T11:39:34Z"
    mac: ENC[AES256_GCM,data:W/1sPNAb5h48KBIWhZlSRaHXttLypnWaIb6c2MvJcgFL1osTle6Hkn9jvy0l+a2ZwlUX9JoO7cD88CrK3o977DsUVBjNMKoLyTTvVlij8tmaBYQ8IU8p+QS7LDSzxpzUpch+N/rNiO+9DlDaTcKPQ9PfuCIH3U04ffV7U5d0aLw=,iv:DbWzRkulv6+xCyeqIDBnQivXQZ369dQM3p9J+zI30EM=,tag:+wOX2/sTOczjNrC1EOe9Yw==,type:str]
    version: 3.13.3
